name: CI/CD for Online Book Library

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Start backend server
        run: npm run server &
      
      - name: Start frontend server
        run: npm run start &
      
      - name: Wait for servers to start
        run: sleep 5

      - name: Install Playwright
        run: npx playwright install chromium

      - name: Run tests
        run: npx playwright test

      - name: Deploy Backend to Render
        if: github.ref == 'refs/heads/main'
        uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.RENDER_BACKEND_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          wait_deploy: true

      - name: Deploy Frontend to Render
        if: github.ref == 'refs/heads/main'
        uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.RENDER_FRONTEND_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          wait_deploy: true

      - name: Update GitHub commit status
        if: github.ref == 'refs/heads/main'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha,
              state: 'success',
              target_url: 'https://your-library-app.onrender.com',
              description: 'Deployment succeeded',
              context: 'Deployment to Render'
            })
