name: CI/CD for Online Book Library

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Start backend server
        run: npm run server &
      
      - name: Start frontend server
        run: npm run start &
      
      - name: Wait for servers to start
        run: sleep 5

      - name: Run Playwright tests
        run: npx playwright install
        run: npx playwright test
      


